version: '3'

services:
  postgres:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
    container_name: GamesBD
    volumes:
      - ./postgres_data:/var/lib/postgresql
    ports:
      - 5432:5432
